#!/usr/bin/env python3

import argparse
import pykickstart

from pykickstart.parser import *
from pykickstart.version import makeVersion
from pykickstart.commands.repo import F27, F27_Repo, F27_RepoData

from jinja2 import Environment

REPO_TEMPLATE = """
[{{ks_repo.name}}]
name={{ks_repo.name}}
enabled=1
{%- if ks_repo.baseurl %}
baseurl={{ks_repo.baseurl}}
{%- endif -%}
{%- if ks_repo.metalink %}
metalink={{ks_repo.metalink}}
{%- endif -%}
{%- if ks_repo.gpgkey %}
gpgcheck=1
gpgkey={{ks_repo.gpgkey}}
{% else %}
gpgcheck=0
{% endif -%}
"""


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--ks",
        metavar='PATH',
        required=True
    )
    parser.add_argument(
        "--extract-repo-conf-to",
        metavar='PATH',
        required=False
    )
    parser.add_argument(
        "--extract-packages-to",
        metavar='PATH',
        required=False
    )
    return parser.parse_args()


class Qubes_RepoData(F27_RepoData):
    removedKeywords = F27_RepoData.removedKeywords
    removedAttrs = F27_RepoData.removedAttrs

    def __init__(self, *args, **kwargs):
        F27_RepoData.__init__(self, *args, **kwargs)
        self.gpgkey = kwargs.get("gpgkey", "")

    def _getArgsAsStr(self):
        retval = F27_RepoData._getArgsAsStr(self)

        if self.gpgkey:
            retval += " --gpgkey=\"%s\"" % self.gpgkey

        return retval


class Qubes_Repo(F27_Repo):
    removedKeywords = F27_Repo.removedKeywords
    removedAttrs = F27_Repo.removedAttrs

    def __init__(self, *args, **kwargs):
        F27_Repo.__init__(self, *args, **kwargs)

    def _getParser(self):
        op = F27_Repo._getParser(self)
        op.add_argument("--gpgkey", action="store", version=F27,
                        help="Specify GPG key to used to the corresponding repo")

        return op


pykickstart.commands.repo.F30_Repo = Qubes_Repo
pykickstart.commands.repo.F30_RepoData = Qubes_RepoData


def main():
    args = get_args()
    if args.ks:
        handler = makeVersion()
        ksparser = KickstartParser(handler)
        ksparser.readKickstart(args.ks)

        repo_content = ''

        if args.extract_repo_conf_to:
            for ks_repo in ksparser.handler.repo.repoList:
                repo_content += Environment().from_string(REPO_TEMPLATE).render(
                    ks_repo=ks_repo.__dict__)

            try:
                with open(args.extract_repo_conf_to, 'w') as repo_fd:
                    repo_fd.write(repo_content)
            except EnvironmentError:
                print(
                    "Cannot write repo file to %s" % args.extract_repo_conf_to)
                return 1

        if args.extract_packages_to:
            packages = []
            for group in ksparser.handler.packages.groupList:
                packages.append('@%s' % group.name)

            for pkg in ksparser.handler.packages.packageList:
                packages.append('%s' % pkg)

            try:
                with open(args.extract_packages_to, 'w') as pkgs_fd:
                    pkgs_fd.write(' '.join(packages))
            except EnvironmentError:
                print(
                    "Cannot write packages list to %s" % args.extract_packages_to)
                return 1


if __name__ == '__main__':
    sys.exit(main())
